services:
  api:
    build:
      context: .
    ports:
      - "8787:8787"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mydb
      - DIRECT_DATABASE_URL=postgresql://postgres:postgres@db:5432/mydb
      - JWT_SECRET=local_dev_secret_key
    command: sh -c "pnpm migrate && pnpm dev"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:16
    container_name: postgres_local
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
